package com.models;
// Generated Jun 17, 2015 12:29:59 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Mblfprlin generated by hbm2java
 */
public class Mblfprlin  implements java.io.Serializable {


     private BigDecimal id;
     private Date mtgl;
     private String mslsno;
     private String prlin;
     private String prliname;

    public Mblfprlin() {
    }

	
    public Mblfprlin(BigDecimal id) {
        this.id = id;
    }
    public Mblfprlin(BigDecimal id, Date mtgl, String mslsno, String prlin, String prliname) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.prlin = prlin;
       this.prliname = prliname;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Date getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(Date mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getPrlin() {
        return this.prlin;
    }
    
    public void setPrlin(String prlin) {
        this.prlin = prlin;
    }
    public String getPrliname() {
        return this.prliname;
    }
    
    public void setPrliname(String prliname) {
        this.prliname = prliname;
    }




}


