package com.models;
// Generated Jun 17, 2015 12:29:59 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Mblftpr3d5 generated by hbm2java
 */
public class Mblftpr3d5  implements java.io.Serializable {


     private BigDecimal id;
     private Date mtgl;
     private String mslsno;
     private String kode;
     private BigDecimal xno;
     private BigDecimal minrange;
     private BigDecimal maxrange;
     private BigDecimal tpercent;
     private BigDecimal tvalue;
     private BigDecimal tqty;
     private String txqty;

    public Mblftpr3d5() {
    }

	
    public Mblftpr3d5(BigDecimal id) {
        this.id = id;
    }
    public Mblftpr3d5(BigDecimal id, Date mtgl, String mslsno, String kode, BigDecimal xno, BigDecimal minrange, BigDecimal maxrange, BigDecimal tpercent, BigDecimal tvalue, BigDecimal tqty, String txqty) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.kode = kode;
       this.xno = xno;
       this.minrange = minrange;
       this.maxrange = maxrange;
       this.tpercent = tpercent;
       this.tvalue = tvalue;
       this.tqty = tqty;
       this.txqty = txqty;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Date getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(Date mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getKode() {
        return this.kode;
    }
    
    public void setKode(String kode) {
        this.kode = kode;
    }
    public BigDecimal getXno() {
        return this.xno;
    }
    
    public void setXno(BigDecimal xno) {
        this.xno = xno;
    }
    public BigDecimal getMinrange() {
        return this.minrange;
    }
    
    public void setMinrange(BigDecimal minrange) {
        this.minrange = minrange;
    }
    public BigDecimal getMaxrange() {
        return this.maxrange;
    }
    
    public void setMaxrange(BigDecimal maxrange) {
        this.maxrange = maxrange;
    }
    public BigDecimal getTpercent() {
        return this.tpercent;
    }
    
    public void setTpercent(BigDecimal tpercent) {
        this.tpercent = tpercent;
    }
    public BigDecimal getTvalue() {
        return this.tvalue;
    }
    
    public void setTvalue(BigDecimal tvalue) {
        this.tvalue = tvalue;
    }
    public BigDecimal getTqty() {
        return this.tqty;
    }
    
    public void setTqty(BigDecimal tqty) {
        this.tqty = tqty;
    }
    public String getTxqty() {
        return this.txqty;
    }
    
    public void setTxqty(String txqty) {
        this.txqty = txqty;
    }




}


