package com.models;
// Generated Jun 17, 2015 12:29:59 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Mblftpr3h generated by hbm2java
 */
public class Mblftpr3h  implements java.io.Serializable {


     private BigDecimal id;
     private Date mtgl;
     private String mslsno;
     private String kode;
     private String ket;
     private String flagtype;
     private String flaggrup;
     private String flgout;
     private String flagrange;
     private String pctpr;
     private String flagsypc;
     private BigDecimal flagjmlpc;
     private String flagmult;
     private BigDecimal selllimit;
     private BigDecimal multipercent;
     private BigDecimal multvalue;
     private BigDecimal multqty;
     private String multxqty;
     private String begdate;
     private String enddate;
     private BigDecimal minbeli;
     private BigDecimal nbrutto;
     private String pctpr1;
     private String pctpr2;
     private String pctpr3;
     private String pctpr4;
     private String pctpr5;
     private String pctpr6;
     private String pctpr7;
     private String pctpr8;
     private String pctpr9;

    public Mblftpr3h() {
    }

	
    public Mblftpr3h(BigDecimal id) {
        this.id = id;
    }
    public Mblftpr3h(BigDecimal id, Date mtgl, String mslsno, String kode, String ket, String flagtype, String flaggrup, String flgout, String flagrange, String pctpr, String flagsypc, BigDecimal flagjmlpc, String flagmult, BigDecimal selllimit, BigDecimal multipercent, BigDecimal multvalue, BigDecimal multqty, String multxqty, String begdate, String enddate, BigDecimal minbeli, BigDecimal nbrutto, String pctpr1, String pctpr2, String pctpr3, String pctpr4, String pctpr5, String pctpr6, String pctpr7, String pctpr8, String pctpr9) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.kode = kode;
       this.ket = ket;
       this.flagtype = flagtype;
       this.flaggrup = flaggrup;
       this.flgout = flgout;
       this.flagrange = flagrange;
       this.pctpr = pctpr;
       this.flagsypc = flagsypc;
       this.flagjmlpc = flagjmlpc;
       this.flagmult = flagmult;
       this.selllimit = selllimit;
       this.multipercent = multipercent;
       this.multvalue = multvalue;
       this.multqty = multqty;
       this.multxqty = multxqty;
       this.begdate = begdate;
       this.enddate = enddate;
       this.minbeli = minbeli;
       this.nbrutto = nbrutto;
       this.pctpr1 = pctpr1;
       this.pctpr2 = pctpr2;
       this.pctpr3 = pctpr3;
       this.pctpr4 = pctpr4;
       this.pctpr5 = pctpr5;
       this.pctpr6 = pctpr6;
       this.pctpr7 = pctpr7;
       this.pctpr8 = pctpr8;
       this.pctpr9 = pctpr9;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Date getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(Date mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getKode() {
        return this.kode;
    }
    
    public void setKode(String kode) {
        this.kode = kode;
    }
    public String getKet() {
        return this.ket;
    }
    
    public void setKet(String ket) {
        this.ket = ket;
    }
    public String getFlagtype() {
        return this.flagtype;
    }
    
    public void setFlagtype(String flagtype) {
        this.flagtype = flagtype;
    }
    public String getFlaggrup() {
        return this.flaggrup;
    }
    
    public void setFlaggrup(String flaggrup) {
        this.flaggrup = flaggrup;
    }
    public String getFlgout() {
        return this.flgout;
    }
    
    public void setFlgout(String flgout) {
        this.flgout = flgout;
    }
    public String getFlagrange() {
        return this.flagrange;
    }
    
    public void setFlagrange(String flagrange) {
        this.flagrange = flagrange;
    }
    public String getPctpr() {
        return this.pctpr;
    }
    
    public void setPctpr(String pctpr) {
        this.pctpr = pctpr;
    }
    public String getFlagsypc() {
        return this.flagsypc;
    }
    
    public void setFlagsypc(String flagsypc) {
        this.flagsypc = flagsypc;
    }
    public BigDecimal getFlagjmlpc() {
        return this.flagjmlpc;
    }
    
    public void setFlagjmlpc(BigDecimal flagjmlpc) {
        this.flagjmlpc = flagjmlpc;
    }
    public String getFlagmult() {
        return this.flagmult;
    }
    
    public void setFlagmult(String flagmult) {
        this.flagmult = flagmult;
    }
    public BigDecimal getSelllimit() {
        return this.selllimit;
    }
    
    public void setSelllimit(BigDecimal selllimit) {
        this.selllimit = selllimit;
    }
    public BigDecimal getMultipercent() {
        return this.multipercent;
    }
    
    public void setMultipercent(BigDecimal multipercent) {
        this.multipercent = multipercent;
    }
    public BigDecimal getMultvalue() {
        return this.multvalue;
    }
    
    public void setMultvalue(BigDecimal multvalue) {
        this.multvalue = multvalue;
    }
    public BigDecimal getMultqty() {
        return this.multqty;
    }
    
    public void setMultqty(BigDecimal multqty) {
        this.multqty = multqty;
    }
    public String getMultxqty() {
        return this.multxqty;
    }
    
    public void setMultxqty(String multxqty) {
        this.multxqty = multxqty;
    }
    public String getBegdate() {
        return this.begdate;
    }
    
    public void setBegdate(String begdate) {
        this.begdate = begdate;
    }
    public String getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(String enddate) {
        this.enddate = enddate;
    }
    public BigDecimal getMinbeli() {
        return this.minbeli;
    }
    
    public void setMinbeli(BigDecimal minbeli) {
        this.minbeli = minbeli;
    }
    public BigDecimal getNbrutto() {
        return this.nbrutto;
    }
    
    public void setNbrutto(BigDecimal nbrutto) {
        this.nbrutto = nbrutto;
    }
    public String getPctpr1() {
        return this.pctpr1;
    }
    
    public void setPctpr1(String pctpr1) {
        this.pctpr1 = pctpr1;
    }
    public String getPctpr2() {
        return this.pctpr2;
    }
    
    public void setPctpr2(String pctpr2) {
        this.pctpr2 = pctpr2;
    }
    public String getPctpr3() {
        return this.pctpr3;
    }
    
    public void setPctpr3(String pctpr3) {
        this.pctpr3 = pctpr3;
    }
    public String getPctpr4() {
        return this.pctpr4;
    }
    
    public void setPctpr4(String pctpr4) {
        this.pctpr4 = pctpr4;
    }
    public String getPctpr5() {
        return this.pctpr5;
    }
    
    public void setPctpr5(String pctpr5) {
        this.pctpr5 = pctpr5;
    }
    public String getPctpr6() {
        return this.pctpr6;
    }
    
    public void setPctpr6(String pctpr6) {
        this.pctpr6 = pctpr6;
    }
    public String getPctpr7() {
        return this.pctpr7;
    }
    
    public void setPctpr7(String pctpr7) {
        this.pctpr7 = pctpr7;
    }
    public String getPctpr8() {
        return this.pctpr8;
    }
    
    public void setPctpr8(String pctpr8) {
        this.pctpr8 = pctpr8;
    }
    public String getPctpr9() {
        return this.pctpr9;
    }
    
    public void setPctpr9(String pctpr9) {
        this.pctpr9 = pctpr9;
    }




}


