package com.models;
// Generated Jun 17, 2015 12:29:59 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Mblftpr3d1 generated by hbm2java
 */
public class Mblftpr3d1  implements java.io.Serializable {


     private BigDecimal id;
     private Date mtgl;
     private String mslsno;
     private String kode;
     private String typeout;

    public Mblftpr3d1() {
    }

	
    public Mblftpr3d1(BigDecimal id) {
        this.id = id;
    }
    public Mblftpr3d1(BigDecimal id, Date mtgl, String mslsno, String kode, String typeout) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.kode = kode;
       this.typeout = typeout;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Date getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(Date mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getKode() {
        return this.kode;
    }
    
    public void setKode(String kode) {
        this.kode = kode;
    }
    public String getTypeout() {
        return this.typeout;
    }
    
    public void setTypeout(String typeout) {
        this.typeout = typeout;
    }




}


