package com.models;
// Generated Jun 17, 2015 12:29:59 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Mblftransfer generated by hbm2java
 */
public class Mblftransfer  implements java.io.Serializable {


     private BigDecimal id;
     private Date mtgl;
     private String mslsno;
     private String cekno;
     private String custno;
     private String bank;
     private String tglcek;
     private BigDecimal nilaicek;
     private BigDecimal nilaibyr;
     private String flag;
     private String flagscy;

    public Mblftransfer() {
    }

	
    public Mblftransfer(BigDecimal id) {
        this.id = id;
    }
    public Mblftransfer(BigDecimal id, Date mtgl, String mslsno, String cekno, String custno, String bank, String tglcek, BigDecimal nilaicek, BigDecimal nilaibyr, String flag, String flagscy) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.cekno = cekno;
       this.custno = custno;
       this.bank = bank;
       this.tglcek = tglcek;
       this.nilaicek = nilaicek;
       this.nilaibyr = nilaibyr;
       this.flag = flag;
       this.flagscy = flagscy;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Date getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(Date mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getCekno() {
        return this.cekno;
    }
    
    public void setCekno(String cekno) {
        this.cekno = cekno;
    }
    public String getCustno() {
        return this.custno;
    }
    
    public void setCustno(String custno) {
        this.custno = custno;
    }
    public String getBank() {
        return this.bank;
    }
    
    public void setBank(String bank) {
        this.bank = bank;
    }
    public String getTglcek() {
        return this.tglcek;
    }
    
    public void setTglcek(String tglcek) {
        this.tglcek = tglcek;
    }
    public BigDecimal getNilaicek() {
        return this.nilaicek;
    }
    
    public void setNilaicek(BigDecimal nilaicek) {
        this.nilaicek = nilaicek;
    }
    public BigDecimal getNilaibyr() {
        return this.nilaibyr;
    }
    
    public void setNilaibyr(BigDecimal nilaibyr) {
        this.nilaibyr = nilaibyr;
    }
    public String getFlag() {
        return this.flag;
    }
    
    public void setFlag(String flag) {
        this.flag = flag;
    }
    public String getFlagscy() {
        return this.flagscy;
    }
    
    public void setFlagscy(String flagscy) {
        this.flagscy = flagscy;
    }




}


