package com.models;
// Generated Jun 17, 2015 12:29:59 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Mblfstcust generated by hbm2java
 */
public class Mblfstcust  implements java.io.Serializable {


     private BigDecimal id;
     private Date mtgl;
     private String mslsno;
     private String custno;
     private String pcode;
     private String pcodename;
     private String unit1;
     private String unit2;
     private String unit3;
     private BigDecimal convunit2;
     private BigDecimal convunit3;
     private BigDecimal sellprice1;
     private BigDecimal sellprice2;
     private BigDecimal sellprice3;
     private BigDecimal qty;
     private String xqty;
     private String prlin;
     private String brand;

    public Mblfstcust() {
    }

	
    public Mblfstcust(BigDecimal id) {
        this.id = id;
    }
    public Mblfstcust(BigDecimal id, Date mtgl, String mslsno, String custno, String pcode, String pcodename, String unit1, String unit2, String unit3, BigDecimal convunit2, BigDecimal convunit3, BigDecimal sellprice1, BigDecimal sellprice2, BigDecimal sellprice3, BigDecimal qty, String xqty, String prlin, String brand) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.custno = custno;
       this.pcode = pcode;
       this.pcodename = pcodename;
       this.unit1 = unit1;
       this.unit2 = unit2;
       this.unit3 = unit3;
       this.convunit2 = convunit2;
       this.convunit3 = convunit3;
       this.sellprice1 = sellprice1;
       this.sellprice2 = sellprice2;
       this.sellprice3 = sellprice3;
       this.qty = qty;
       this.xqty = xqty;
       this.prlin = prlin;
       this.brand = brand;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Date getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(Date mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getCustno() {
        return this.custno;
    }
    
    public void setCustno(String custno) {
        this.custno = custno;
    }
    public String getPcode() {
        return this.pcode;
    }
    
    public void setPcode(String pcode) {
        this.pcode = pcode;
    }
    public String getPcodename() {
        return this.pcodename;
    }
    
    public void setPcodename(String pcodename) {
        this.pcodename = pcodename;
    }
    public String getUnit1() {
        return this.unit1;
    }
    
    public void setUnit1(String unit1) {
        this.unit1 = unit1;
    }
    public String getUnit2() {
        return this.unit2;
    }
    
    public void setUnit2(String unit2) {
        this.unit2 = unit2;
    }
    public String getUnit3() {
        return this.unit3;
    }
    
    public void setUnit3(String unit3) {
        this.unit3 = unit3;
    }
    public BigDecimal getConvunit2() {
        return this.convunit2;
    }
    
    public void setConvunit2(BigDecimal convunit2) {
        this.convunit2 = convunit2;
    }
    public BigDecimal getConvunit3() {
        return this.convunit3;
    }
    
    public void setConvunit3(BigDecimal convunit3) {
        this.convunit3 = convunit3;
    }
    public BigDecimal getSellprice1() {
        return this.sellprice1;
    }
    
    public void setSellprice1(BigDecimal sellprice1) {
        this.sellprice1 = sellprice1;
    }
    public BigDecimal getSellprice2() {
        return this.sellprice2;
    }
    
    public void setSellprice2(BigDecimal sellprice2) {
        this.sellprice2 = sellprice2;
    }
    public BigDecimal getSellprice3() {
        return this.sellprice3;
    }
    
    public void setSellprice3(BigDecimal sellprice3) {
        this.sellprice3 = sellprice3;
    }
    public BigDecimal getQty() {
        return this.qty;
    }
    
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }
    public String getXqty() {
        return this.xqty;
    }
    
    public void setXqty(String xqty) {
        this.xqty = xqty;
    }
    public String getPrlin() {
        return this.prlin;
    }
    
    public void setPrlin(String prlin) {
        this.prlin = prlin;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }




}


