package com.models;
// Generated Jun 17, 2015 12:29:59 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Mblfrute generated by hbm2java
 */
public class Mblfrute  implements java.io.Serializable {


     private BigDecimal id;
     private Date mtgl;
     private String mslsno;
     private String norute;
     private String custno;
     private String flag;
     private String stVisit;
     private BigDecimal amount;
     private BigDecimal jmlvisit;

    public Mblfrute() {
    }

	
    public Mblfrute(BigDecimal id) {
        this.id = id;
    }
    public Mblfrute(BigDecimal id, Date mtgl, String mslsno, String norute, String custno, String flag, String stVisit, BigDecimal amount, BigDecimal jmlvisit) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.norute = norute;
       this.custno = custno;
       this.flag = flag;
       this.stVisit = stVisit;
       this.amount = amount;
       this.jmlvisit = jmlvisit;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Date getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(Date mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getNorute() {
        return this.norute;
    }
    
    public void setNorute(String norute) {
        this.norute = norute;
    }
    public String getCustno() {
        return this.custno;
    }
    
    public void setCustno(String custno) {
        this.custno = custno;
    }
    public String getFlag() {
        return this.flag;
    }
    
    public void setFlag(String flag) {
        this.flag = flag;
    }
    public String getStVisit() {
        return this.stVisit;
    }
    
    public void setStVisit(String stVisit) {
        this.stVisit = stVisit;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public BigDecimal getJmlvisit() {
        return this.jmlvisit;
    }
    
    public void setJmlvisit(BigDecimal jmlvisit) {
        this.jmlvisit = jmlvisit;
    }




}


