package com.models;
// Generated Jun 17, 2015 12:29:59 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Mblfgrupout generated by hbm2java
 */
public class Mblfgrupout  implements java.io.Serializable {


     private BigDecimal id;
     private Date mtgl;
     private String mslsno;
     private String groupout;
     private String groupname;

    public Mblfgrupout() {
    }

	
    public Mblfgrupout(BigDecimal id) {
        this.id = id;
    }
    public Mblfgrupout(BigDecimal id, Date mtgl, String mslsno, String groupout, String groupname) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.groupout = groupout;
       this.groupname = groupname;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Date getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(Date mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getGroupout() {
        return this.groupout;
    }
    
    public void setGroupout(String groupout) {
        this.groupout = groupout;
    }
    public String getGroupname() {
        return this.groupname;
    }
    
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }




}


