package com.models;
// Generated Jun 17, 2015 12:29:59 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Mblftypeout generated by hbm2java
 */
public class Mblftypeout  implements java.io.Serializable {


     private BigDecimal id;
     private Date mtgl;
     private String mslsno;
     private String type;
     private String typename;

    public Mblftypeout() {
    }

	
    public Mblftypeout(BigDecimal id) {
        this.id = id;
    }
    public Mblftypeout(BigDecimal id, Date mtgl, String mslsno, String type, String typename) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.type = type;
       this.typename = typename;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Date getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(Date mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getTypename() {
        return this.typename;
    }
    
    public void setTypename(String typename) {
        this.typename = typename;
    }




}


