package com.models;
// Generated Jun 17, 2015 12:29:59 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Mblfgdisc generated by hbm2java
 */
public class Mblfgdisc  implements java.io.Serializable {


     private BigDecimal id;
     private Date mtgl;
     private String mslsno;
     private String gdisc;
     private String gddiscname;

    public Mblfgdisc() {
    }

	
    public Mblfgdisc(BigDecimal id) {
        this.id = id;
    }
    public Mblfgdisc(BigDecimal id, Date mtgl, String mslsno, String gdisc, String gddiscname) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.gdisc = gdisc;
       this.gddiscname = gddiscname;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Date getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(Date mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getGdisc() {
        return this.gdisc;
    }
    
    public void setGdisc(String gdisc) {
        this.gdisc = gdisc;
    }
    public String getGddiscname() {
        return this.gddiscname;
    }
    
    public void setGddiscname(String gddiscname) {
        this.gddiscname = gddiscname;
    }




}


