package com.models;
// Generated Jun 17, 2015 12:29:59 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonFormat;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.annotations.Type;
import org.joda.time.LocalDate;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Mblfaktivitas generated by hbm2java
 */
public class Mblfaktivitas  implements java.io.Serializable {


     private BigDecimal id;
      @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyyMMdd")
     private String mtgl;
     private String mslsno;
     private String kode;
     private String kodea;
     private String ket;

    public Mblfaktivitas() {
    }

	
    public Mblfaktivitas(BigDecimal id) {
        this.id = id;
    }
    public Mblfaktivitas(BigDecimal id, String mtgl, String mslsno, String kode, String kodea, String ket) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.kode = kode;
       this.kodea = kodea;
       this.ket = ket;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    
    
    public String getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(String mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getKode() {
        return this.kode;
    }
    
    public void setKode(String kode) {
        this.kode = kode;
    }
    public String getKodea() {
        return this.kodea;
    }
    
    public void setKodea(String kodea) {
        this.kodea = kodea;
    }
    public String getKet() {
        return this.ket;
    }
    
    public void setKet(String ket) {
        this.ket = ket;
    }

}


