package com.models;
// Generated Jun 17, 2015 12:29:59 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Mblfpriced generated by hbm2java
 */
public class Mblfpriced  implements java.io.Serializable {


     private BigDecimal id;
     private Date mtgl;
     private String mslsno;
     private String id2;
     private BigDecimal selprice1;
     private BigDecimal selprice2;
     private BigDecimal selprice3;

    public Mblfpriced() {
    }

	
    public Mblfpriced(BigDecimal id) {
        this.id = id;
    }
    public Mblfpriced(BigDecimal id, Date mtgl, String mslsno, String id2, BigDecimal selprice1, BigDecimal selprice2, BigDecimal selprice3) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.id2 = id2;
       this.selprice1 = selprice1;
       this.selprice2 = selprice2;
       this.selprice3 = selprice3;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Date getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(Date mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getId2() {
        return this.id2;
    }
    
    public void setId2(String id2) {
        this.id2 = id2;
    }
    public BigDecimal getSelprice1() {
        return this.selprice1;
    }
    
    public void setSelprice1(BigDecimal selprice1) {
        this.selprice1 = selprice1;
    }
    public BigDecimal getSelprice2() {
        return this.selprice2;
    }
    
    public void setSelprice2(BigDecimal selprice2) {
        this.selprice2 = selprice2;
    }
    public BigDecimal getSelprice3() {
        return this.selprice3;
    }
    
    public void setSelprice3(BigDecimal selprice3) {
        this.selprice3 = selprice3;
    }




}


