package com.models;
// Generated Jun 17, 2015 12:29:59 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Mblfprice generated by hbm2java
 */
public class Mblfprice  implements java.io.Serializable {


     private BigDecimal id;
     private Date mtgl;
     private String mslsno;
     private String gharga;
     private String pcode;
     private BigDecimal selprice1;
     private BigDecimal selprice2;
     private BigDecimal selprice3;

    public Mblfprice() {
    }

	
    public Mblfprice(BigDecimal id) {
        this.id = id;
    }
    public Mblfprice(BigDecimal id, Date mtgl, String mslsno, String gharga, String pcode, BigDecimal selprice1, BigDecimal selprice2, BigDecimal selprice3) {
       this.id = id;
       this.mtgl = mtgl;
       this.mslsno = mslsno;
       this.gharga = gharga;
       this.pcode = pcode;
       this.selprice1 = selprice1;
       this.selprice2 = selprice2;
       this.selprice3 = selprice3;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Date getMtgl() {
        return this.mtgl;
    }
    
    public void setMtgl(Date mtgl) {
        this.mtgl = mtgl;
    }
    public String getMslsno() {
        return this.mslsno;
    }
    
    public void setMslsno(String mslsno) {
        this.mslsno = mslsno;
    }
    public String getGharga() {
        return this.gharga;
    }
    
    public void setGharga(String gharga) {
        this.gharga = gharga;
    }
    public String getPcode() {
        return this.pcode;
    }
    
    public void setPcode(String pcode) {
        this.pcode = pcode;
    }
    public BigDecimal getSelprice1() {
        return this.selprice1;
    }
    
    public void setSelprice1(BigDecimal selprice1) {
        this.selprice1 = selprice1;
    }
    public BigDecimal getSelprice2() {
        return this.selprice2;
    }
    
    public void setSelprice2(BigDecimal selprice2) {
        this.selprice2 = selprice2;
    }
    public BigDecimal getSelprice3() {
        return this.selprice3;
    }
    
    public void setSelprice3(BigDecimal selprice3) {
        this.selprice3 = selprice3;
    }




}


